### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by algady** [AstronomyAPI/Samples#14]
Hi, I'm interested in this project, but I wasn't able to get started using it so far.
Usually, I get (API-KEY) that I use to send requests, but I wasn't sure where to get one and how to sent the request itself!
I'm using C#, and I hope that you can help me and sorry if this is not the right wat to contact you, best regards. Algady

**Comment by astroanu** [comment]
Hi, don't think the programming language you're using really matters. Did you read the getting started section in the documentation ?  https://docs.astronomyapi.com/

**Comment by algady** [comment]
> Hi, don't think the programming language you're using really matters. Did you read the getting started section in the documentation ? https://docs.astronomyapi.com/

Hi and thanks for your reply, Yes I did, but it wasn't so clear how to do it, I created an account but after that I couldn't find any api-key
What I need is how can I send a request? usually the request looks like: http://api.openweathermap.org/data/2.5/weather?q={city%20name}&appid={API%20key} this example from openweathermap.org service.

**Comment by algady** [comment]
Hi, the following part is what I don't understand from docs page!
---------------------------------
Basic Authentication
When making API calls to endpoints which require authentication, you must use the credentials obtained above to create a hash. The algorithm to create the hash is very simple. Below are implementations on several commonly used languages.
JS
const hash = btoa(`${applicationId}:${applicationSecret}`);
PHP
$hash = base64_encode("$applicationId:$applicationSecret");
The generated hash must be provided in the API request's Authorization header, after the term Basic followed by a space.
"Authorization: Basic <hash>"
---------------------------------

**Comment by astroanu** [comment]
When you login and go to the dashboard you should see the create application button, where you can obtain your application id and the secret.

You need to provide both the application id and the secret as the basic authentication header when making requests
This might help https://stackoverflow.com/questions/4334521/httpwebrequest-using-basic-authentication

**Comment by algady** [comment]
Hi and thanks again, first of all, when I create application it asks me for "Origin", what is that? 
Secondly, after I get application Id and secret I need to run a command like "const hash = btoa(`${applicationId}:${applicationSecret}`);" I know that I need to use my application Id and secret, but how I run that command?
I only use c#, so this php and js command are not so easy to me!

**Comment by astroanu** [comment]
origin is the domain you're planning to call the api from, this is valid only if you're calling from a browser. Otherwise just give it some value to passthrough.

btoa is a js function to create a base64 string, i've put a link how you can do the same in c# above.

**Comment by algady** [comment]
ok, I read that post, now I did some progress, I'm using the following code to send a request but I got StatusCode: 403, ReasonPhrase: 'Forbidden
-------
```
var http = new HttpClient();
                string username = "70d8120d-297a-4c6b-84d7-6e08e1bc0e41";
                string password = "e75c473ee82882357fcf71d8a2a7cb4be5aadb64e36e1b4f0976ca0f5ecaac8dbee91a285050f06dd8212eeaff3e2e6eea8e7170854cf40899dabde10311729e4ae1fce4e8e79c9d4a4d2d6e2298e05c4ff27e303c8f2efd51892323327e06697a7707656a7e802efd0f701aa60b73a3";
                String encoded = System.Convert.ToBase64String(System.Text.Encoding.GetEncoding("ISO-8859-1").GetBytes(username + ":" + password));

                var response = await http.GetAsync("https://api.astronomyapi.com/api/v2/bodies' \\ --header 'Authorization: Basic "+encoded+"' \\");
                var result = await response.Content.ReadAsStringAsync();
                var serializer = new DataContractJsonSerializer(typeof(Root));
                var ms = new MemoryStream(Encoding.UTF8.GetBytes(result));
                var data_4 = (Root)serializer.ReadObject(ms);
                return data_4;
```
Any help please?
I know that I'm tacking some of your time, and I'm considering to give some donation if you help me get this to work!
thanks

**Comment by astroanu** [comment]
can you sen the `encoded` string here. so i can take a look. ?

also try UTC-8 instead of ISO-8859-1

**Comment by algady** [comment]
This is the code:
NzBkODEyMGQtMjk3YS00YzZiLTg0ZDctNmUwOGUxYmMwZTQxOmU3NWM0NzNlZTgyODgyMzU3ZmNmNzFkOGEyYTdjYjRiZTVhYWRiNjRlMzZlMWI0ZjA5NzZjYTBmNWVjYWFjOGRiZWU5MWEyODUwNTBmMDZkZDgyMTJlZWFmZjNlMmU2ZWVhOGU3MTcwODU0Y2Y0MDg5OWRhYmRlMTAzMTE3MjllNGFlMWZjZTRlOGU3OWM5ZDRhNGQyZDZlMjI5OGUwNWM0ZmYyN2UzMDNjOGYyZWZkNTE4OTIzMjMzMjdlMDY2OTdhNzcwNzY1NmE3ZTgwMmVmZDBmNzAxYWE2MGI3M2Ez

**Comment by astroanu** [comment]
I don't exactly know why your c# code isn't working, as i don't have any experience in that language.

your encoded string is valid

**Comment by algady** [comment]
Maybe the request format isn't correct!
Can you please send me a request example from your project for example to request the moon phase?

**Comment by astroanu** [comment]
Hi, this is curl code it's working fine with your username and password

`curl --location --request POST 'https://api.astronomyapi.com/api/v2/studio/moon-phase' \
--header 'Authorization: Basic  <hash>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "format": "png",
    "style": {
        "moonStyle": "sketch",
        "backgroundStyle": "stars",
        "backgroundColor": "black",
        "headingColor": "white",
        "textColor": "white"
    },
    "observer": {
        "latitude": 40.712772,
        "longitude": -73.935242,
        "date": "2020-10-28"
    },
    "view": {
        "type": "portrait-simple"
    }
}'`

**Comment by algady** [comment]
I've managed to make it works, with such request: `https://api.astronomyapi.com/api/v2/bodies/positions?latitude=42.4304&longitude=19.2593&from_date=2018-12-20&to_date=2018-12-22&time=08:00:00&elevation=50`
this is simple (string) format.
but not sure how to send different request that require different formatting like this: `'{ "format": "png", "style": { "moonStyle": "sketch", "backgroundStyle": "stars", "backgroundColor": "black", "headingColor": "white", "textColor": "white" }, "observer": { "latitude": 40.712772, "longitude": -73.935242, "date": "2020-10-28" }, "view": { "type": "portrait-simple" } }'`
This one is not (string) but (object) and not sure how to include it in my requests!

**Comment by astroanu** [comment]
have you tried encoding the object as a json string ?

**Comment by algady** [comment]
Hi, sorry I was sick last couple of weeks, I've managed to make it works, but still having trouble to get "_**generate an image of an area in the sky**_"  to work!
I'm using this page which allows me to test my [request,](https://rapidapi.com/astronomyapi-astronomyapi-default/api/astronomy?endpoint=apiendpoint_9934f3a9-b36f-4883-b322-64c3e1dce468) but no lock so far! this is my request:
{
    "observer": {
        "latitude": 33.775867,
        "longitude": -84.39733,
        "date": "2019-12-20"
    },
    "view": {
        "type": "area",
        "parameters": {
            "position": {
                "equatorial": {
                    "rightAscension": 14.83,
                    "declination": -15.23
                }
            },
            "zoom": 3 //optional
        }
    }
}
Thanks

**Comment by astroanu** [comment]
what response are you getting ? 
are you calling the api via rapid api proxy or directly ?

**Comment by algady** [comment]
> what response are you getting ?
> are you calling the api via rapid api proxy or directly ?

I've just managed to make it works, in the documentation page of astronomyAPI they said that **"// Note how this request does not have the field `style`"** and the sample request they gave also dose not have this field (style)
but I added this field to my request and it's working now as expected.
this is my new request:
{
    "observer": {
        "latitude": 33.775867,
        "longitude": -84.39733,
        "date": "2019-02-03"
    },
    "style":"default",
    "view": {
        "type": "area",
        "parameters": {
            "position": {
                "equatorial": {
                    "rightAscension": 14.83,
                    "declination": -15.23
                }
            },
            "zoom": 3
        }
    }
}

**Comment by astroanu** [comment]
Hi, i think i've found a bug, thanks for bringing this up.
You may use the style: as default for now, which the docs says optional but it's actually require. 
Will be putting a fix for this in the next release.

**Comment by barakforkids** [comment]
> ISO-8859-1

I'm steel getting 403 error, 
Can you send a sample connection to the api with security check that works?
