### ISSUE TITLE
Moonphase rotated

### ISSUE THREAD

**Issue by Romkabouter** [AstronomyAPI/Samples#18]
Hi there,

I was investigating the moonphase api and the image looks nice.
However, the moonphase seems to be rotated. The Last Quarter is show as First Quarter and also all other phase look incorrectly rotated.
It seems that the image has northern and southern hemisfere switched

**Comment by astroanu** [comment]
Hi, thanks for noticing this. Will take a look.

**Comment by Romkabouter** [comment]
Thanks, I also noticed the phase is called Wanning Crescent instead of Waning :)

**Comment by astroanu** [comment]
Hi, the calculations are based on an observer facing south, so it's similar to looking at a star chart. Can you compare again with stellarium's results ?

**Comment by astroanu** [comment]
> Thanks, I also noticed the phase is called Wanning Crescent instead of Waning :)

i've fixed the typo

**Comment by Romkabouter** [comment]
![image](https://user-images.githubusercontent.com/4774478/110367941-a0e07f80-8048-11eb-81fc-9c563aca484c.png)

https://widgets.astronomyapi.com/moon-phase/generated/39aee462857eff122591a617e12deda04868186854f1e64b0f52916d31e34c8d.svg

**Comment by astroanu** [comment]
Could you send me the payload you're sending. It seems to be something related to your lat,long.

**Comment by Romkabouter** [comment]
Hi,



Nice to hear from you



This is my payload:



payload = {
    "format": "svg",
    "style": {
        "moonStyle": "default",
        "backgroundStyle": "solid",
        "backgroundColor": "none",
        "headingColor": "white",
        "textColor": "red"
    },
    "observer": {
        "longitude": 6.217736911719457,
        "latitude": 53.02531493986979,
        "date": "2021-03-08"
    },
    "view": {
        "type": "portrait-simple"
    }
}
 Entering those values in https://www.gps-coordinates.net/ give the correct position (see attachement). You can see "Donkerbroek" in the stellarium screenshot as well



Regards and glad to help,



Paul





-----Oorspronkelijk bericht-----
Afzender: astroanu <notifications@github.com>
Verstuurd: Maandag 8 Maart 2021 20:22
Aan: AstronomyAPI/Samples <Samples@noreply.github.com>
Cc: Paul Romkes <paul@newbreedmedia.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [AstronomyAPI/Samples] Moonphase rotated (#18)


Could you send me the payload you're sending. It seems to be something related to your lat,long.

**Comment by astroanu** [comment]
I'm not sure what exactly was the problem but these the images i generated. 

https://widgets.astronomyapi.com/moon-phase/generated/402a266de480117c0e52b8e72b5d5178a206295ff7d615d7e51ae7a3753fcad1.svg

https://widgets.astronomyapi.com/moon-phase/generated/c24464410b717824057e6eb52c1242bb49040df6aeee7ab4f582b7aa99cd0e15.png

btw svg images has an alignment issue we're aware.

**Comment by Romkabouter** [comment]
That is might strange, looks good to me!

I have tried calling it again and now generates the correct image :)
https://widgets.astronomyapi.com/moon-phase/generated/402a266de480117c0e52b8e72b5d5178a206295ff7d615d7e51ae7a3753fcad1.svg

**Comment by astroanu** [comment]
hey, must be something with the cache key. i'll take a look later. happy to help. :)
