### ISSUE TITLE
http://api.astronomyapi.org down

### ISSUE THREAD

**Issue by aquilo** [AstronomyAPI/Samples#2]
Hi, the last days I always get an error when attempting to connect to api.astronomyapi.org: 

This site can’t be reached api.astronomyapi.org refused to connect.
ERR_CONNECTION_REFUSED

Is this a temporary problem? It would be very sad if this beautiful API didn't exist anymore.
Thanks, Adrian

**Comment by astroanu** [comment]
Should be up again. 

Haven't been much of an improvement lately. Been very busy with stuff :(
