### ISSUE TITLE
Authentication fails with "not a valid key=value pair (missing equal-sign)"

### ISSUE THREAD

**Issue by cmxl** [AstronomyAPI/Samples#20]
I'm using Postman and want to GET https://api.astronomyapi.com/api/bodies
I add my Authorization Header: `Basic myfancyappidandsecrethash`
The result is a 403 with the following message:

```json
{
	"message": "'ZDQ...' not a valid key=value pair (missing equal-sign) in Authorization header: 'Basic ZDQ...'."
}
```

I generated the hash with atob(`${appid}:${appsecret}`);
Even if I add the Origin header (Domain from Dashboard) in the request I still get the same exact error.

**Comment by astroanu** [comment]
the url should be `https://api.astronomyapi.com/api/v2/bodies` can you try with that please ?
