### ISSUE TITLE
Uncaught (in promise) Error: Request failed with status code 422

### ISSUE THREAD

**Issue by JeromeSaby** [AstronomyAPI/Samples#21]
I'm trying your sample code in firefox (windows 10). 
Unfortunately I only manage to make "Planetary Positions" work.

The two others (Star Charts & Moon Phase) throw an `Uncaught (in promise) Error: Request failed with status code 422` whatever I do.
All the fields are filled. Could you help me with this issue ?

Thanks.

**Comment by astroanu** [comment]
Hi, to help you further can you please post the payload you're using. thanks.
