### ISSUE TITLE
Import statement in components has wrong filename

### ISSUE THREAD

**Issue by milkwitch** [AstronomyAPI/Samples#33]
The components MoonPhase.vue, Positions.vue, and StarChart.vue all have the GoBack.vue import file path spelled wrong.
It says `import GoBack from "./Goback.vue"`  and should say `import GoBack from "./GoBack.vue"`.

Thank you for this awesome example project!

**Comment by astroanu** [comment]
Thanks. If you could send a PR that would be nice.

**Comment by astroanu** [comment]
This is now fixed
