### ISSUE TITLE
Endpoint expects float type values instead of strings

### ISSUE THREAD

**Issue by milkwitch** [AstronomyAPI/Samples#34]
The studio endpoint seems to want floats for latitude and longitude instead of strings.  The v-model in MoonPhase.vue can be updated to float, and I think the data function has to be updated?  I'm not actually familiar with vue, so I'm not certain, but that's what I did to fix it.
Thanks again for this great example

**Comment by astroanu** [comment]
Thanks, if you could send a PR it would be nice

**Comment by astroanu** [comment]
This is now fixed
