### ISSUE TITLE
what about galaxies data

### ISSUE THREAD

**Issue by BurierAbdalwahhabElia** [AstronomyAPI/Samples#52]
hi, i know that i must pull new request, but this didn't work for some error.
i need data about galaxies. can i get?
thank you

**Comment by astroanu** [comment]
The search endpoint should do it. At the moment only name and coordinates works as filters. So the endpoint can only be used if you know the full or part of the name of the object or if you're searching for objects within an area in the sky. 

May I know your requirement? Maybe we could add it as a feature.
