### ISSUE TITLE
Changing "observer" props does not update the image

### ISSUE THREAD

**Issue by MikaCinc** [AstronomyAPI/Samples#58]
I'm using the [https://docs.astronomyapi.com/endpoints/studio/star-chart](star-chart) api:

```
await fetch("https://api.astronomyapi.com/api/v2/studio/star-chart", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    Authorization: `Basic ${authString}`,
  },
  body: JSON.stringify({
    style: "default",
    observer: {
      latitude: 30.04440,
      longitude: 45.23570,
      date: "2021-12-10",
    },
    view: {
      type: "area",
      parameters: {
        position: {
          equatorial: {
            rightAscension: 14.83,
            declination: -10.23,
          },
        },
        zoom: 3, //optional
      },
    },
  }),
})
```

If anything inside **view** changes I get an updated image but if I change any **observer** prop (latitude, longitude or date) I get the new URL but the image stays exactly the same...

**Comment by astroanu** [comment]
Thanks for reporting. Seems to be a bug around rendering. We'll take a look.

**Comment by astroanu** [comment]
Closing as this should be fixed by now.

**Comment by thibauth01** [comment]
@astroanu 
I seem to have the same problem now.
When I change the latitude, longitude or date, the image always stays the same.
