### ISSUE TITLE
Acceess from Application

### ISSUE THREAD

**Issue by Oshi01** [AstronomyAPI/Samples#60]
From your Docs
"Be sure to set the Origin to the domain of the website when creating an application. If you're planning to use the API on a webpage"

Can i ask what should be used if the API is to be used from An Application, or in my case, from a Wolfram Mathematica Notebook.

Any help much appreciated

Paul

**Comment by astroanu** [comment]
Hi, it's used to allow cross domain access if you're calling the API from a web browser so only the calls made from your website are allowed from the specific application id.

However at the moment, it's just ignored. We allow requests from any domain.
