### ISSUE TITLE
Image text is weird for certain dates

### ISSUE THREAD

**Issue by SarahG18** [AstronomyAPI/Samples#63]
Hi! For some reason, when a certain date is input, the moon phase generated is fine but the text isn't actual text, it's some sort of tables with numbers. Is there a way to fix this in the HTML code? 
<img width="276" alt="Screenshot 2023-11-26 200036" src="https://github.com/AstronomyAPI/Samples/assets/152116960/e79495a7-705f-49bb-8c30-7cc9faae05e1">

**Comment by astroanu** [comment]
Seems like a bug. Will take a look.

**Comment by SarahG18** [comment]
Thanks!

**Comment by astroanu** [comment]
This should be fixed now.
