### ISSUE TITLE
Credentials invalid

### ISSUE THREAD

**Issue by SarahG18** [AstronomyAPI/Samples#64]
Hello!

I am trying to reach the API and it says that the header is missing and validation fails. I know it's the correct App ID and secret so is there a reason why this is occuring? Thanks!

**Comment by astroanu** [comment]
Hi, can you post the code you're using without the credentials? then we can check.

**Comment by ziriuz84** [comment]
I have the same problem, but also when I try to connect to playground. I just created new credentials without success

**Comment by ahoink** [comment]
> I have the same problem, but also when I try to connect to playground. I just created new credentials without success

Same problem here, started over the weekend. my guess is something with their API has changed and/or is down. Either way it sounds like it's on their end if multiple people are suddenly having the same problem.

**Comment by glitterer** [comment]
Same problem with me as well. Currently getting Credential Validation failed message. Also, while trying to use this api in my iOS app, the api fails to be reached. But funnily, the API Usage from my dashboard says "success" when it actually hasn't. 
Is there any fix in this?

**Comment by astroanu** [comment]
Please re-open if the issue persisits.
