### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by EloxFire** [AstronomyAPI/Samples#66]
Hi,

I'm having trouble with CORS when requesting the API.
I've set the origin to http://localhost on my dashboard, my appid and app secret are good but iI still get CORS.

What am I doing wrong ?
![image_2024-01-30_174140908](https://github.com/AstronomyAPI/Samples/assets/43670144/0112533b-8096-4096-9945-74f079894e67)

**Comment by ahoink** [comment]
Seems related to #64 
I think there's a problem on the server side

**Comment by EloxFire** [comment]
API seems to beworking again :)
