### ISSUE TITLE
Star charts are failing

### ISSUE THREAD

**Issue by gdpodesta** [AstronomyAPI/Samples#68]
Tried several different iterations from your site, but all result in this:

 POST https://api.astronomyapi.com/api/v2/studio/star-chart 503 (Service Unavailable)
createError.js:17 Uncaught (in promise) Error: Request failed with status code 503
    at createError (createError.js:17:1)
    at settle (settle.js:18:1)
    at XMLHttpRequest.handleLoad (xhr.js:62:1)
﻿

**Comment by astroanu** [comment]
Hi, the new updates should fix this issue.
