### ISSUE TITLE
origin when calling from not web apps ?

### ISSUE THREAD

**Issue by cladelpino** [AstronomyAPI/Samples#74]
Hi, I'm getting  this error when trying to access the API from a client (Android Tasker app) {"Message":"User is not authorized to access this resource with an explicit deny"}

I was not able to set an empty origin since I don't plan to use it from web apps. I set it to http://localhost. 

What should be the right settings to access the API from non web apps clients?

thanks in advance

**Comment by astroanu** [comment]
Origin was implemented long time ago but it's unused at this moment and probably will be removed in the future. 

Since you're calling from a server it doesn't matter anyway. You can put your website domain or any domain you like.
