### ISSUE TITLE
Access-Control-Allow-Origin wildcard "*" error

### ISSUE THREAD

**Issue by Megastrik3** [AstronomyAPI/Samples#80]
Please use this template to ask your question so I can answer you better

## Description of the issue
When creating a POST request to the api with my auth key, I am blocked by the CORS policy citing that my Access-Control-Allow-Origin header is the wildcard "*" which is not allowed.
## What did you try and what didn't work
I tried two different domains with fresh app ID and app secrets, and made sure I was copying them properly.
I'm not entirely sure where to go from here, as I can't tell if this is an issue with my code, or an issue with the way I created my app.
## Example code (if applicable)
This is the code that I am using:
`
    const data = {\"style\":{\"moonStyle\":\"default\",\"backgroundStyle\":\"solid\",\"backgroundColor\":\"#ffffff\",\"headingColor\":\"#000000\",\"textColor\":\"#000000\"},\"observer\":{\"latitude\":43.778467,\"longitude\":-74.39033,\"date\":\"${moonDate}\"},\"view\":{\"type\":\"portrait-simple\",\"parameters\":{}}};

    const xhr = new XMLHttpRequest();
    xhr.withCredentials = true;
    
    xhr.addEventListener("readystatechange", function () {
      if (this.readyState === this.DONE) {
        console.log(this.responseText);
      }
    });
    
    xhr.open("POST", "https://api.astronomyapi.com/api/v2/studio/moon-phase");
    xhr.setRequestHeader("Authorization", "Basic " + btoa());

    xhr.send();
}
`
## Application ID (this will help trace the logs to see what went wrong)
809b1cfe-8b23-410b-b437-4774f5831104

**Comment by astroanu** [comment]
xhr.withCredentials = true; <--- this is the problem. set this to false.

**Comment by Megastrik3** [comment]
Awesome! Thank you for your help!
